-- vim.api.nvim_set_var("neovide_cursor_vfx_mode", "torpedo")
vim.api.nvim_set_var("neovide_cursor_vfx_mode", "pixiedust")
vim.api.nvim_set_var("neovide_cursor_vfx_particle_lifetime", 25)
vim.api.nvim_set_var("neovide_cursor_vfx_particle_density", 3)
vim.api.nvim_set_var("neovide_cursor_vfx_particle_speed", 3)
vim.api.nvim_set_var("neovide_cursor_vfx_particle_phase", 5)
vim.api.nvim_set_var("neovide_cursor_vfx_particle_curl", 5)
vim.api.nvim_set_var("neovide_cursor_trail_length", 0.8)
vim.api.nvim_set_var("neovide_refresh_rate", 60)
-- vim.api.nvim_set_var("neovide_remember_window_size", true)
-- vim.api.nvim_set_var("neovide_fullscreen", true)
vim.api.nvim_set_var("neovide_cursor_antialiasing", false)
vim.api.nvim_set_var("neovide_cursor_vfx_opacity", 500)
vim.api.nvim_set_var("neovide_transparency", 1)
vim.api.nvim_set_var("neovide_floating_blur", 1)
vim.api.nvim_set_var("neovide_window_floating_opacity", 1)
